version: '3.7'

services:
  api:
    build: ./classification
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./classification/:/app/
    ports:
      - 8001:8000